#!/bin/sh
set -e
if [ ! -f /etc/ShellCrash/start.sh ]; then
    echo "sc-init: Initializing /etc/ShellCrash from backup"
    cp -a /etc/ShellCrash.init/. /etc/ShellCrash/
    echo "sc-init: Done"
else
    echo "sc-init: ShellCrash already initialized, skipping"
fi
