#!/bin/sh
set -e

if [ -z "$(ls -A /etc/ShellCrash)" ]; then
    echo "shellcrash: initializing /etc/ShellCrash from backup"
    cp -r /etc/ShellCrash_backup/* /etc/ShellCrash/
    echo "successfully initialized"
fi

. /etc/ShellCrash/configs/command.env

exec /bin/sh -c "${COMMAND} > /dev/null"
